# Contains URLs needed for testing

class TestData(object):
    MAIN_URL = "https://www.flickr.com/"
    LOGIN_URL = "https://identity.flickr.com/login"
    SIGNUP_URL = "https://identity.flickr.com/sign-up"
    ACCOUNT_URL = "https://www.flickr.com/account"
    HELP_URL = "https://help.flickr.com/"
    PRIVACY_URL = "https://www.flickr.com/help/privacy"
    TERMS_URL = "https://www.flickr.com/help/terms"
    YAHOO_REDIRECT_URL = "https://login.yahoo.com/"
    ABOUT_URL = "https://www.flickr.com/about"
    JOBS_URL = "https://www.flickr.com/jobs"
    BLOG_URL = "https://blog.flickr.net/en"
    DEVELOPERS_URL = "https://www.flickr.com/services/developer"
    GUIDELINES_URL = "https://www.flickr.com/help/guidelines"
    HELP_FORUM_URL = "https://www.flickr.com/help/forum/en-us/"
    COOKIES_URL = "https://www.flickr.com/help/cookies"
    CHECK_EMAIL_URL = "https://identity.flickr.com/check-email/sign-up"
    PASSWORD_CHANGE_URL = "https://identity.flickr.com/change-password"
    PASSWORD_CHANGE_SUCCESS_URL = "https://identity.flickr.com/change-complete/change-password"
    ACCOUNT_DELETE_URL = "https://www.flickr.com/account/delete"
    PROFILE_EDIT_URL = "https://www.flickr.com/profile_edit.gne?from=personal"
    DISPLAY_NAME_URL = "https://www.flickr.com/account/prefs/screenname/?from=personal"
    FLICKR_MAIL_URL = "https://www.flickr.com/mail"
    RECENT_ACTIVITY_URL = "https://www.flickr.com/activity"
    FORGOT_PASSWORD_URL = "https://identity.flickr.com/forgot-password"
    CHECK_EMAIL_FORGOT_PASS_URL = "https://identity.flickr.com/check-email/forgot-password"
